config/routes.rb
Rails.application.routes.draw do
  resources :factures
  resources :clients
  resources :products do 
    collection {post :import}
  end
  resources :users, only: [:index]
  devise_for :users
  root to: "users#index"

  post 'add_user', to: "users#add_user"
  get 'form_user', to: "users#form_user"
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :factures
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result(distinct: true)
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:nom, :email, :encours)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :encours %>
    <%= form.text_field :encours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<div class='row'>
  <div class='col-md-3'>
    <%= search_form_for @q do |f| %>

      <%= f.label :nom %>
      <%= f.search_field :nom_cont %>
      <br>
      <%= f.label :email %>
      <%= f.search_field :email_cont %>
      <br>
      <%= f.label :encours %>
      <%= f.search_field :encours_eq %>
      <br>
      <%= f.submit %>
      <% end %>
  </div>

  <div class='col-md-9'>
    <table>
      <thead>
        <tr>
          <th>Nom</th>
          <th>Email</th>
          <th>Encours</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.nom %></td>
            <td><%= client.email %></td>
            <td><%= client.encours %></td>
            <td><%= link_to 'Show', client %></td>
            <td><%= link_to 'Edit', edit_client_path(client) %></td>
            <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <%= link_to 'New Client', new_client_path %>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @client.nom %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Encours:</strong>
  <%= @client.encours %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>