config/routes.rb
Rails.application.routes.draw do
  resources :factures
  resources :clients
  resources :products do 
    collection {post :import}
  end
  resources :users, only: [:index]
  devise_for :users
  root to: "users#index"

  post 'add_user', to: "users#add_user"
  get 'form_user', to: "users#form_user"
end

app/models/facture.rb
class Facture < ApplicationRecord
    belongs_to :user
    belongs_to :client
    has_many :lignefactures


    REGELEMENT = ["Espéce", "Chèque", "Virement"]
    def self.regelement
        REGELEMENT.map { |t| [t, t]}
    end
end

app/controllers/factures_controller.rb
class FacturesController < ApplicationController
  before_action :set_facture, only: [:show, :edit, :update, :destroy]

  # GET /factures
  # GET /factures.json
  def index
    @factures = Facture.all
  end

  # GET /factures/1
  # GET /factures/1.json
  def show
  end

  # GET /factures/new
  def new
    @facture = Facture.new
  end

  # GET /factures/1/edit
  def edit
  end

  # POST /factures
  # POST /factures.json
  def create
    @facture = Facture.new(facture_params)

    respond_to do |format|
      if @facture.save
        format.html { redirect_to @facture, notice: 'Facture was successfully created.' }
        format.json { render :show, status: :created, location: @facture }
      else
        format.html { render :new }
        format.json { render json: @facture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factures/1
  # PATCH/PUT /factures/1.json
  def update
    respond_to do |format|
      if @facture.update(facture_params)
        format.html { redirect_to @facture, notice: 'Facture was successfully updated.' }
        format.json { render :show, status: :ok, location: @facture }
      else
        format.html { render :edit }
        format.json { render json: @facture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factures/1
  # DELETE /factures/1.json
  def destroy
    @facture.destroy
    respond_to do |format|
      format.html { redirect_to factures_url, notice: 'Facture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facture
      @facture = Facture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def facture_params
      params.require(:facture).permit(:n_facute, :date, :code_client, :cree_bar, :montant_ttc, :montant_ht, :montant_tva, :est_valid, :est_regle, :mode_reglement)
    end
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/views/factures/_form.html.erb
<%= form_for(@facture, local: true) do |form| %>
  <% if facture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facture.errors.count, "error") %> prohibited this facture from being saved:</h2>

      <ul>
        <% facture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :n_facute %>
    <%= form.number_field :n_facute %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :code_client %>
    <%= form.text_field :code_client %>
  </div>

  <div class="field">
    <%= form.label :cree_bar %>
    <%= form.number_field :cree_bar %>
  </div>

  <div class="field">
    <%= form.label :montant_ttc %>
    <%= form.text_field :montant_ttc %>
  </div>

  <div class="field">
    <%= form.label :montant_ht %>
    <%= form.number_field :montant_ht %>
  </div>

  <div class="field">
    <%= form.label :montant_tva %>
    <%= form.number_field :montant_tva %>
  </div>

  <div class="field">
    <%= form.label :est_valid %>
    <%= form.check_box :est_valid %>
  </div>

  <div class="field">
    <%= form.label :est_regle %>
    <%= form.check_box :est_regle %>
  </div>

  <div class="field">
    <%= form.label :mode_reglement %>
    <%= form.select :mode_reglement, collection: Facture.regelement %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/factures/edit.html.erb
<h1>Editing Facture</h1>

<%= render 'form', facture: @facture %>

<%= link_to 'Show', @facture %> |
<%= link_to 'Back', factures_path %>

app/views/factures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Factures</h1>

<table>
  <thead>
    <tr>
      <th>N facute</th>
      <th>Date</th>
      <th>Code client</th>
      <th>Cree bar</th>
      <th>Montant ttc</th>
      <th>Montant ht</th>
      <th>Montant tva</th>
      <th>Est valid</th>
      <th>Est regle</th>
      <th>Mode reglement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @factures.each do |facture| %>
      <tr>
        <td><%= facture.n_facute %></td>
        <td><%= facture.date %></td>
        <td><%= facture.code_client %></td>
        <td><%= facture.cree_bar %></td>
        <td><%= facture.montant_ttc %></td>
        <td><%= facture.montant_ht %></td>
        <td><%= facture.montant_tva %></td>
        <td><%= facture.est_valid %></td>
        <td><%= facture.est_regle %></td>
        <td><%= facture.mode_reglement %></td>
        <td><%= link_to 'Show', facture %></td>
        <td><%= link_to 'Edit', edit_facture_path(facture) %></td>
        <td><%= link_to 'Destroy', facture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facture', new_facture_path %>

app/views/factures/new.html.erb
<h1>New Facture</h1>

<%= render 'form', facture: @facture %>

<%= link_to 'Back', factures_path %>

app/views/factures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>N facute:</strong>
  <%= @facture.n_facute %>
</p>

<p>
  <strong>Date:</strong>
  <%= @facture.date %>
</p>

<p>
  <strong>Code client:</strong>
  <%= @facture.code_client %>
</p>

<p>
  <strong>Cree bar:</strong>
  <%= @facture.cree_bar %>
</p>

<p>
  <strong>Montant ttc:</strong>
  <%= @facture.montant_ttc %>
</p>

<p>
  <strong>Montant ht:</strong>
  <%= @facture.montant_ht %>
</p>

<p>
  <strong>Montant tva:</strong>
  <%= @facture.montant_tva %>
</p>

<p>
  <strong>Est valid:</strong>
  <%= @facture.est_valid %>
</p>

<p>
  <strong>Est regle:</strong>
  <%= @facture.est_regle %>
</p>

<p>
  <strong>Mode reglement:</strong>
  <%= @facture.mode_reglement %>
</p>

<%= link_to 'Edit', edit_facture_path(@facture) %> |
<%= link_to 'Back', factures_path %>