config/routes.rb
Rails.application.routes.draw do
  resources :factures
  resources :clients
  resources :products do 
    collection {post :import}
  end
  resources :users, only: [:index]
  devise_for :users
  root to: "users#index"

  post 'add_user', to: "users#add_user"
  get 'form_user', to: "users#form_user"
end

app/views/layouts/_header.html.erb
<div class="col padding-0">
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        <%= link_to "Users", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to "sing up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "log in", new_user_session_path, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
                <%= link_to "Produits", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Clients", clients_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Facture", factures_path, class: "nav-link" %>
            </li>
          <% if current_user.has_role? :admin %>
            <li class="nav-item">
                <%= link_to "Add utilisateur", form_user_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu left-position" aria-labelledby="navbarDropdown">
              <%= link_to "Edt profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Sing out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>
</div>

  

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show w-100" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogiTest1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <div class="row">
          <%= render "layouts/header" %> 
        </div>
        <div class="row">
          <%= render "layouts/messages" %> 
        </div>
        <%= yield %>
    </div>
  </body>
</html>